### ISSUE TITLE
Request for Paper Reference Mentioned in the Repository

### ISSUE THREAD

**Issue by tensor2023** [YuanZhouhang/VQ-MAGE-Med#1]
Hello. I recently came across your interesting repository on GitHub, and I am very interested in the work you have done. However, I could not find the paper that is mentioned in the repository. Could you please provide me with a reference or a link to the paper? It would be very helpful for my research.

**Comment by YuanZhouhang** [comment]
Hello, we are very honored that you are interested in our work. Our work has been accepted for the MICCAI2024 conference, but the article is still not publicly available as the conference has not started yet. The MICCAI2024 conference will begin on October 6, 2024, and we will update the link and citation of our article in the GitHub repository in the future when the article is publicly available.

**Comment by tensor2023** [comment]
Thank you. Looking forward to it.
